version: '3.8'
 
services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD= "password"
            - MYSQL_DATABASE=seewear
    api:
        build: .
        ports:
            - 8080:80