version: '3.8'
 
services:
    db:
        image: postgres:11
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=seewear
    api:
        build: .
        volumes:
            - .:/app
        ports:
            - 8080:80