name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  build:
    name: Build android app
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master

    - name: Install node modules
      run: |
        yarn install
        
    - name: Cache Gradle Wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - name: Cache Gradle Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-
          
    - name: Make Gradlew Executable
      run: cd android && chmod +x ./gradlew

    - name: Build Android App Bundle
      run: |
        cd android && ./gradlew bundleRelease --no-daemon
        
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
<<<<<<< HEAD
        if: ${{ success() }}
      - name: Make changes to pull request
      
=======

      - name: Make changes to pull request
>>>>>>> 2c3304f1f5919b8286e121e6b3f3a1c0568f1226
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
<<<<<<< HEAD
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
        
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
=======
        uses: danco-2106/T-ESP-Seewear@v1
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
>>>>>>> 2c3304f1f5919b8286e121e6b3f3a1c0568f1226
          signoff: false
          branch: main
          delete-branch: true
          title: 'Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
<<<<<<< HEAD

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
=======
          labels: |
            report
            automated 
>>>>>>> 2c3304f1f5919b8286e121e6b3f3a1c0568f1226
          assignees: benbaoulema
          reviewers: benbaoulema
          team-reviewers: |
            owners
            maintainers
          draft: false
<<<<<<< HEAD

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
=======
>>>>>>> 2c3304f1f5919b8286e121e6b3f3a1c0568f1226
