name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - features
      - main
  push:
    branches:
      - features
      - develop
      - main

jobs:
  build:
    name: Build android app
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master

    - name: Install node modules
      run: |
        yarn install
        
    - name: Cache Gradle Wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - name: Cache Gradle Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-
          
    - name: Make Gradlew Executable
      run: cd android && chmod +x ./gradlew

    - name: Build Android App Bundle
      run: |
        cd android && ./gradlew bundleRelease --no-daemon
        
    - name: Build Android App Apk
      run: |
        cd android && ./gradlew build
        
    - name: Cherche build
      run: |
        tree android/app/build/outputs
        
    - name: Upload a Bundle release Artifact
      uses:  actions/upload-artifact@v2.2.4
      with:
        name: android-bundle
        path: android/build/outputs/release/bundle/app-release.aab
        
    - name: Upload apk Artifact
      uses:  actions/upload-artifact@v2.2.4
      with:
        name: android-apk
        path: android/build/outputs/apk/debug/app-debug.apk


    
